apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-spinnaker-account
  namespace: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-spinnaker-role
  namespace: jenkins
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-spinnaker-role-binding
  namespace: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-spinnaker-role
subjects:
- kind: ServiceAccount
  name: jenkins-spinnaker-account
  namespace: jenkins
